platform :ios, '8.0'
inhibit_all_warnings!

target 'PLShortVideoKitDemo' do
   pod "PLShortVideoKit", :path => "../"
   pod 'Qiniu', '7.1.7'
   pod 'Fabric', '1.6.11'
   pod 'Crashlytics', '3.8.4'
   pod 'Masonry', '1.0.2'
   pod 'FLAnimatedImage', '1.0.12'
   pod 'PLPlayerKit', '3.3.1'
end
