platform :ios, '8.0'
inhibit_all_warnings!

target 'PLShortVideoKitDemo' do
   pod "PLShortVideoKit", :path => "../"
   pod 'Fabric', '1.6.11'
   pod 'Crashlytics', '3.8.4'
   pod 'Masonry', '1.0.2'
   pod 'Qiniu', '7.1.5'
   pod 'PLPlayerKit', '2.4.3'
end
