#ifndef GPUImageColorConversion_h
#define GPUImageColorConversion_h


extern GLfloat *LSQKColorConversion601;
extern GLfloat *LSQKColorConversion601FullRange;
extern GLfloat *LSQKColorConversion709;
extern NSString *const LSQKGPUImageYUVVideoRangeConversionForRGFragmentShaderString;
extern NSString *const LSQKGPUImageYUVFullRangeConversionForLAFragmentShaderString;
extern NSString *const LSQKGPUImageYUVVideoRangeConversionForLAFragmentShaderString;

#endif 
